-
  name: Execute two commands on localhost
  hosts: localhost
  tasks:
    -
      name: Execute a date command
      command: date
    -
      name: Execute a command to display the hosts file
      command: cat /etc/hosts
